# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_banner_hotsearchwords_indexad_slide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe6\x95\xb0\xe9\x87\x8f')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5546\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u5546\u54c1\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe5\x8f\xb7')),
                ('trade_no', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'\xe4\xba\xa4\xe6\x98\x93\xe5\x8f\xb7')),
                ('pay_status', models.SmallIntegerField(choices=[(0, b'\xe4\xba\xa4\xe6\x98\x93\xe6\x88\x90\xe5\x8a\x9f'), (1, b'\xe4\xba\xa4\xe6\x98\x93\xe8\xb6\x85\xe6\x97\xb6'), (2, b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xa4\xe6\x98\x93'), (3, b'\xe4\xba\xa4\xe6\x98\x93\xe7\xbb\x93\xe6\x9d\x9f'), (4, b'\xe5\xbe\x85\xe6\x94\xaf\xe4\xbb\x98')], default=4, verbose_name=b'\xe4\xba\xa4\xe6\x98\x93\xe7\x8a\xb6\xe6\x80\x81')),
                ('message', models.CharField(max_length=256, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x95\x99\xe8\xa8\x80')),
                ('order_amount', models.FloatField(default=0.0, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe9\x87\x91\xe9\xa2\x9d')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe6\x97\xb6\xe9\x97\xb4')),
                ('address', models.CharField(default=b'', max_length=200, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80')),
                ('picker_name', models.CharField(default=b'', max_length=32, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe5\xa7\x93\xe5\x90\x8d')),
                ('picker_phone', models.IntegerField(default=b'', verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe7\x94\xb5\xe8\xaf\x9d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe6\x89\x80\xe5\xb1\x9e\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name=b'\xe8\xb4\xad\xe7\x89\xa9\xe8\xbd\xa6\xe4\xb8\xad\xe7\x9a\x84\xe8\xb4\xa7\xe7\x89\xa9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe8\xb4\xad\xe7\x89\xa9\xe8\xbd\xa6\xe6\x89\x80\xe5\xb1\x9e\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OrderInfo', verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
