# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_banner_hotsearchwords_indexad_slide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default=b'', max_length=64, verbose_name=b'\xe7\x9c\x81\xe4\xbb\xbd')),
                ('city', models.CharField(default=b'', max_length=64, verbose_name=b'\xe5\xb8\x82')),
                ('district', models.CharField(default=b'', max_length=128, verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f')),
                ('address_info', models.CharField(default=b'', max_length=256, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbf\xa1\xe6\x81\xaf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u8d27\u5730\u5740',
                'verbose_name_plural': '\u7528\u6237\u6536\u8d27\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.SmallIntegerField(default=0, verbose_name=b'\xe7\x95\x99\xe8\xa8\x80\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('subject', models.CharField(default=b'', max_length=100, verbose_name=b'\xe7\x95\x99\xe8\xa8\x80\xe4\xb8\xbb\xe9\xa2\x98')),
                ('content', models.TextField(default=b'', verbose_name=b'\xe7\x95\x99\xe8\xa8\x80\xe5\x86\x85\xe5\xae\xb9')),
                ('file', models.FileField(upload_to=b'leavingmsg/images/', verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe6\x96\x87\xe4\xbb\xb6')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
