# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'banner', verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe\xe7\x89\x87')),
                ('index', models.IntegerField(default=0, verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe9\xa1\xba\xe5\xba\x8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u5546\u54c1',
                'verbose_name_plural': '\u8f6e\u64ad\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default=b'', max_length=20, verbose_name=b'\xe7\x83\xad\xe6\x90\x9c\xe8\xaf\x8d')),
                ('index', models.IntegerField(default=0, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u70ed\u641c\u8bcd',
                'verbose_name_plural': '\u70ed\u641c\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe7\xb1\xbb\xe7\x9b\xae')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u5546\u54c1\u7c7b\u522b\u5e7f\u544a',
                'verbose_name_plural': '\u9996\u9875\u5546\u54c1\u7c7b\u522b\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u56fe\u7247',
                'verbose_name_plural': '\u5546\u54c1\u56fe\u7247',
            },
        ),
    ]
